# Generated by Django 2.2.4 on 2020-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20200331_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepdf',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='filepdf',
            name='serius',
            field=models.CharField(blank=True, choices=[('mt', 'Математика'), ('ph', 'Физика'), ('bi', 'Биология'), ('ch', 'Химия'), ('pd', 'Педагогика'), ('lt', 'Литература'), ('ek', 'Экономика'), ('pr', 'Право')], default='mt', help_text='Серия публикации', max_length=2),
        ),
    ]
